Add Varint
denosaurs/byte_type pull request #11
Opened 2023-04-12 19:26 UTC by MierenManz

Closes #5

2023-04-12 23:04 UTC, eliassjogreen requested changes
Nice! Looks good, just a few more tests and some renaming and then its perfect 🌟

2023-04-12 23:04 UTC, eliassjogreen commented on types/varint/mod.ts
> +        throw new Error("VarInt is too big");
```suggestion
        throw new TypeError("VarInt is too big");
```

Perhaps a more descriptive error would be nice, `Leb128Varint cannot exceed 32 bits in length` perhaps?

2023-04-12 23:04 UTC, eliassjogreen commented on types/varint/mod.ts
> +export class Leb128Varint implements Type<number> {
Lets rename this to `I32LEB128`, that way we can add `U32LEB128`, `I64LEB128`, `U64LEB128` too in the future? Optionally also move this type to `leb128/mod.ts` instead of the `varint` directory (unless there is interest in implementing other varint variants than leb128).

2023-04-12 23:04 UTC, eliassjogreen commented on types/varint/mod.ts
> +export const leb128Varint = new Leb128Varint();
```suggestion
export const i32leb128 = new I32LEB128();
```

2023-04-12 23:04 UTC, eliassjogreen commented on types/varint/mod_test.ts
- [ ] Also try reading a varint which throws the type error.
- [ ] Try reading and writing `Number.MAX_SAFE_INTEGER` or whatever i32leb128 max value is.

2023-04-13 07:13 UTC, MierenManz commented on types/varint/mod_test.ts
Max value is the same as i32 max

2023-04-13 07:14 UTC, MierenManz commented
Sounds good. Gonna add the suggestions later today

2023-04-15 15:37 UTC, MierenManz commented on types/varint/mod.ts
> +export class Leb128Varint implements Type<number> {
There are variants like zigzag encoded leb128 varints which are used in protobuf. Might be interesting to add those later

2023-04-16 11:16 UTC, eliassjogreen commented on types/varint/mod.ts
> +export class Leb128Varint implements Type<number> {
Alright, lets keep it in `varint` then!

2023-04-20 19:35 UTC, MierenManz commented
@eliassjogreen PTAL

2023-04-21 08:41 UTC, eliassjogreen submitted a review, later dismissed

2023-04-21 08:41 UTC, eliassjogreen commented on types/varint/leb128.ts
> +        throw new Error("VarInt is too big");
```suggestion
        throw new TypeError("I32LEB128 cannot exceed 32 bits in length");
```

2023-04-21 08:41 UTC, eliassjogreen approved these changes

2023-04-21 08:42 UTC, merged